name: Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: '@kapeta'
      - run: npm install
        working-directory: ./codegen-target-golang
      - run: npm run build
        working-directory: ./codegen-target-golang
      - run: npm run test
        working-directory: ./codegen-target-golang
